make:
	icc -O3 -o pfCOZ PF_COZ.cpp -DCO -xhost -AVX  
	icc -O3 -o pfCOZLoop PF_COZ.cpp -DLOOPDP -xhost -AVX 
	icc -O3 -o pfCO PF_CO.cpp -DCO -xhost -AVX
	icc -O3 -o pfCOLoop PF_CO.cpp -DLOOPDP -xhost -AVX
