
@Sort("J")  bit J(int i) { return 1; }
@Sort("J₀") bit J0(int i);
@Sort("J₁") bit J1(int i);
@Sort("K")  bit K(int i) { return 1; }
@Sort("K₀") bit K0(int i);
@Sort("K₁") bit K1(int i);
@Sort("M₀") @Leaf("0") bit M0(int i);
@Sort("M₁") @Leaf("1") bit M1(int i);
@Sort("M₂") @Leaf("2") bit M2(int i);
@Sort("M₃") @Leaf("3") bit M3(int i);
@Sort("L₀") bit L0(int i);
@Sort("L₁") bit L1(int i);
@Sort("L₂") bit L2(int i);
@Sort("L₃") bit L3(int i);


generator void Scope_facts(int n) {
  for (int p = 0 ; p < n ; ++p) {
    assume (J0(p) || J1(p));
    assume (K0(p) || K1(p));
    assume ((L0(p) || L1(p)) == J0(p)); 
    assume ((L2(p) || L3(p)) == J1(p)); 
    assume ((M0(p) || M1(p)) == K0(p)); 
    assume ((M2(p) || M3(p)) == K1(p)); 
    for (int q = 0 ; q < n ; ++q) {
      if (J0(p) && J1(q)) assume(p < q);
      if (K0(p) && K1(q)) assume(p < q);
      if (M0(p) && M1(q)) assume(p < q);
      if (M2(p) && M3(q)) assume(p < q);
      if (L0(p) && L1(q)) assume(p < q);
      if (L2(p) && L3(q)) assume(p < q);
    }
  }
}

generator bit Scope_subsort(int t, int i) {
  if (t == 0) return false;
  else if (t == 1) return L0(i);
  else if (t == 2) return L1(i);
  else if (t == 3) return L2(i);
  else if (t == 4) return L3(i);
  else if (t == 5) return M0(i);
  else if (t == 6) return M1(i);
  else if (t == 7) return M2(i);
  else if (t == 8) return M3(i);
  else if (t == 9) return K0(i);
  else if (t == 10) return K1(i);
  else if (t == 11) return J0(i);
  else if (t == 12) return J1(i);
  else if (t == 13) return J(i);
  else assert(false);
}

generator bit Scope_1d(bit[4] t, int i) {
  return (t[0] && K0(i)) || (t[1] && K1(i)) || (t[2] && K2(i)) || (t[3] && K3(i));
}

generator bit Scope_leaf(int t, int i) {
  if      (t == 0) return L0(i);
  else if (t == 1) return L1(i);
  else if (t == 2) return L2(i);
  else if (t == 3) return L3(i);
  else assert(false);
}

bit Scope_2d(bit[4][4] t, bit lt, int i, int j) {
  bit acc = false;
  /*
  if (t[0][0]) acc = acc || ( Scope_leaf(0, i) && Scope_leaf(0,j) );
  if (t[0][1]) acc = acc || ( Scope_leaf(0, i) && Scope_leaf(1,j) );
  if (t[0][2]) acc = acc || ( Scope_leaf(0, i) && Scope_leaf(2,j) );
  if (t[0][3]) acc = acc || ( Scope_leaf(0, i) && Scope_leaf(3,j) );
  if (t[1][0]) acc = acc || ( Scope_leaf(1, i) && Scope_leaf(0,j) );
  if (t[1][1]) acc = acc || ( Scope_leaf(1, i) && Scope_leaf(1,j) );
  if (t[1][2]) acc = acc || ( Scope_leaf(1, i) && Scope_leaf(2,j) );
  if (t[1][3]) acc = acc || ( Scope_leaf(1, i) && Scope_leaf(3,j) );
  if (t[2][0]) acc = acc || ( Scope_leaf(2, i) && Scope_leaf(0,j) );
  if (t[2][1]) acc = acc || ( Scope_leaf(2, i) && Scope_leaf(1,j) );
  if (t[2][2]) acc = acc || ( Scope_leaf(2, i) && Scope_leaf(2,j) );
  if (t[2][3]) acc = acc || ( Scope_leaf(2, i) && Scope_leaf(3,j) );
  if (t[3][0]) acc = acc || ( Scope_leaf(3, i) && Scope_leaf(0,j) );
  if (t[3][1]) acc = acc || ( Scope_leaf(3, i) && Scope_leaf(1,j) );
  if (t[3][2]) acc = acc || ( Scope_leaf(3, i) && Scope_leaf(2,j) );
  if (t[3][3]) acc = acc || ( Scope_leaf(3, i) && Scope_leaf(3,j) );
  */
  for (int p = 0; p < 4; ++p)
    for (int q = 0; q < 4; ++q)
      if (t[p][q])
        acc = acc || ( Scope_leaf(p, i) && Scope_leaf(q, j) );
  /*
  for (int p = 0; p < 4; ++p)
    for (int q = 0; q < 4; ++q)
      if (t[p][q])
        acc = acc || ((p==0)&&K0(i) || (p==1)&&K1(i) || (p==2)&&K2(i) || (p==3)&&K3(i)) &&
                     ((q==0)&&K0(j) || (q==1)&&K1(j) || (q==2)&&K2(j) || (q==3)&&K3(j));
  */
  if (lt) acc = acc && (i < j);
  return acc;
}

generator int minimal(int i) { minimize(i); return i; }

generator bit minimal_1(bit b) { minimize(b); return b; }
generator bit[4] minimal_4(bit[4] a) { for (int i = 0; i < 4; ++i) minimize(a[i]); return a; }
generator bit[4][4] minimal_4x4(bit[4][4] a) { 
  for (int i = 0; i < 4; ++i) for (int j = 0; j < 4; ++j) minimize(a[i][j]); return a; }
