// Generated by LiveScript 1.4.0
(function(){
  var root, typeVariable;
  root = typeof exports != 'undefined' && exports !== null ? exports : this;
  root.id = function(d){
    return d[0];
  };
  root.tree = function(root, subtrees){
    return {
      $: 'Tree',
      root: root,
      subtrees: subtrees
    };
  };
  root.identifier = function(literal, kind){
    return {
      $: 'Identifier',
      literal: literal,
      kind: kind
    };
  };
  root.genericIdentifier = function(literal){
    return identifier(literal, '?');
  };
  root.variable = function(literal){
    return tree(identifier(literal, 'variable'), []);
  };
  root.abstraction = function(par, body){
    return tree(genericIdentifier('↦'), [par, body]);
  };
  root.application = function(lhs, rhs){
    return tree(genericIdentifier('@'), [lhs, rhs]);
  };
  root.typeOperation = function(op, lhs, rhs){
    return tree(tree(op), [lhs, rhs]);
  };
  typeVariable = function(literal){
    return tree(identifier(literal, 'set'), []);
  };
}).call(this);
