// Generated by LiveScript 1.4.0
(function(){
  var _, x$;
  _ = require('lodash');
  x$ = angular.module('app', ['ui.codemirror', 'ui.select']);
  x$.controller("Ctrl", function($scope){
    $scope.cmOptions = cmOptions();
    $scope.wrapper = function(parent){
      var submitCallback, loadCallback;
      submitCallback = function(cm){
        var calc, thisIdx, nextIdx;
        calc = cm.parent;
        thisIdx = _.findIndex($scope.history, function(h){
          return h.id === calc.id;
        });
        calc.output = "Result of " + calc.input;
        if (thisIdx === $scope.history.length - 1 || typeof $scope.history[thisIdx + 1].output !== 'undefined') {
          nextIdx = _.max($scope.history, function(h){
            return h.id;
          }).id + 1;
          $scope.history.splice(thisIdx + 1, 0, {
            id: nextIdx,
            input: calc.output
          });
        } else {
          $scope.history[thisIdx + 1].input = calc.output;
        }
        cm.getInputField().blur();
        return $scope.$apply();
      };
      loadCallback = function(cm){
        return cm.parent = parent;
      };
      return initEditor(submitCallback, loadCallback);
    };
    $scope.history = [{
      id: 1,
      input: "a b"
    }];
    $scope.output = {};
    $scope.data = [];
  });
}).call(this);
